name: Build images

on:
  push:
    paths:
      - 'runtime/**'
    tags-ignore:
      - '**'

jobs:
  build:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images
        run: make build-images
