name: Build and publish development images

on:
  push:
    paths:
      - 'runtime/**'

jobs:
  publish:
    name: Build and publish development images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build
        run: make build

      - name: Publish images
        run: make publish-dev-images

      - name: Upload builds
        uses: actions/upload-artifact@v2
        with:
          name: php-builds
          path: build
